# define parameters for calibration and identification process
# robot: ur_10
---
calibration:
  calib_level: full_params
  non_geom: False
  base_frame: base_link
  tool_frame: end_link
  markers:
    - ref_joint: G2_gripper_end_joint
      measure: [True, True, True, True, True, True]
  free_flyer: False
  nb_sample: 
identification:
  robot_params:
    - q_lim_def: 1.57 
      dq_lim_def : 5.0 
      ddq_lim_def : 20.0
      tau_lim_def : 4.0
      fv : [0,0,0,0,0,0]
      fs : [0,0,0,0,0,0]
      Ia : None
      offset : None
      Iam6 : None
      fvm6 : None
      fsm6 : None
      N : None
      ratio_essential : None
  problem_params:
    - is_external_wrench : False
      is_joint_torques : True
      force_torque : ['All']
      external_wrench_offsets : False
      has_friction : True
      has_joint_offset : False
      has_actuator_inertia : False
      is_static_regressor : True
      is_inertia_regressor : True
      has_coupled_wrist : False
      embedded_forces : False
  processing_params:
    - cut_off_frequency_butterworth: 10.0
      ts : 0.01
  tls_params:
    - mass_load : 0.48
      which_body_loaded : 5 
      sync_joint_motion : False 
...
